name: record_workspace

environment:
  sdk: ^3.12.0

publish_to: none

dev_dependencies:
  melos: ^7.7.0

workspace:
  - record
  - record/example
  - record_android
  - record_darwin
  - record_linux
  - record_platform_interface
  - record_web
  - record_windows

melos:
  # Don't generate intellij files
  ide:
    intellij: false

  command:
    # When a dependency in a package is listed it will be replaced with the following versions.
    bootstrap:
      environment:
        sdk: ^3.12.0
        flutter: ">=3.44.0"
      dependencies:
        record_platform_interface: ^2.2.0
      dev_dependencies:
        flutter_lints: ^6.0.0

  clean:
    hooks:
      # Runs "flutter clean" in all Flutter packages (`--flutter`) with concurrency
      post: melos exec --flutter -c 1 -- "flutter clean"